### ISSUE TITLE
Parser error: there was a problem parsing the package

### ISSUE THREAD

**Issue by LinArcX** [cnlohr/rawdrawandroid#42] opened 2021-01-01 07:56 UTC
Hello. I've tried to build/push the sample app into my android phone(android 6, not rooted!)

But in final step, it throws some errors on my screen phone.
These are last lines of build process:
```
Verification succesful
#Using the apksigner in this way is only required on Android 30+
/mnt/D/software/linux/IDE/android/sdk/build-tools/30.0.0/apksigner sign --key-pass pass:password --ks-pass pass:password --ks my-release-key.keystore cnfgtest.apk
rm -rf temp.apk
rm -rf makecapk.apk
-rwxrwxrwx 1 linarcx root 45823 Jan  1 11:19 cnfgtest.apk
Installing org.yourorg.cnfgtest
adb install -r cnfgtest.apk
Performing Push Install
cnfgtest.apk: 1 file pushed, 0 skipped. 2.5 MB/s (45823 bytes in 0.017s)
        pkg: /data/local/tmp/cnfgtest.apk
```
Notice that i set `ANDROIDVERSION?=28` in `Makefile`.

**Comment by dreua** [comment] 2021-01-01 09:53
Haven't seen that before, maybe it's worth asking on the discord server. Some things to check:
- Have you followed the general advice on this error when put into Google?
- Can you install other Apps from your PC without problems? Maybe try to compile and install one of the Android Studio examples to make sure.
- What is your phone model?

**Comment by cnlohr** [comment] 2021-01-11 00:28
Definitely hit up the Discord server.  Someone there may know. https://discord.gg/CCeyWyZ

**Comment by LinArcX** [comment] 2021-01-11 15:06
I don't have discord and no interest to use it either.

**Comment by zNoctum** [comment] 2021-03-09 13:03
The problem is that you compile your app with android 30 as target and want to deploy it on a android 23 phone so you just need to change `ANDROIDVERSION` to 23

**Comment by Tanishq-Banyal** [comment] 2021-07-06 04:33
@dreua question should be closed as @zNoctum has provided the correct answer.

**Closed** 2021-07-06 08:27 UTC
Labels: question
